### obtener todos los envios
GET http://localhost:3000/api/envios

### obtener un envio por id
GET http://localhost:3000/api/envios/

### crear un nuevo envio
POST http://localhost:3000/api/envios
Content-Type: application/json

{
    "direccion": "68f1c9413891f5f600c4cf60",
    "fechaEnvio": "05-11-2025",
    "fechaEntregaEstimada": "10-11-2025",
    "fechaEntregaReal": "",
    "estado": "pendiente"
}

### actualizar un envio por id
PUT http://localhost:3000/api/envios/
Content-Type: application/json

{
    "direccion": "id",
    "fechaEnvio": "",
    "fechaEntregaEstimada": "10-11-2025",
    "fechaEntregaReal": "",
    "estado": "enviado"
}

### eliminar un envio por id
DELETE http://localhost:3000/api/envios/
