### obtener todas las marcas
GET http://localhost:3000/api/marcas

### obtener una marca por id
GET http://localhost:3000/api/marcas/68dc29f3855611417f9620d6

### guardar una nueva marca
POST http://localhost:3000/api/marcas
Content-Type: application/json

{
    "nombre": "Lacoste",
    "descripcion": "Elegancia y estilo deportivo",
    "logo": "lacoste_logo.png"
}

### actualizar una marca por id
PUT http://localhost:3000/api/marcas/68f9ab05f9043afdb5058bb2
Content-Type: application/json

{
    "nombre": "IDN Athletics",
    "descripcion": "Ropa deportiva para entrenar",
    "logo": "https://drive.google.com/file/d/1jcXv1d28LY_BOzJROIa2ucuR-VcObT4z"
}

### eliminar una marca por id
DELETE http://localhost:3000/api/marcas/
