### obtener todos los usuarios
GET http://localhost:3000/api/usuarios
### obtener un usuario por id
GET http://localhost:3000/api/usuarios/
### guardar un nuevo usuario
POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "nombre": "Juan",
    "apellido": "Pérez",
    "email": "juanperez@gmail.com",
    "contraseña": "password123",
    "localidad": "6899232cb8ee81cbb90b94ee",
    "direccion": "Calle Falsa 123",
    "telefono": "1234567890"
}
### actualizar un usuario por id
PUT http://localhost:3000/api/usuarios/
Content-Type: application/json
{
    "nombre": "Guillermo",
    "apellido": "Gonzalez",
    "email": "guillermogonzalez@gmail.com",
    "contraseña": "newpassword456",
    "localidad": "6899232cb8ee81cbb90b94ee",
    "direccion": "Avenida Siempre Viva 742",
    "telefono": "0987654321"
}
### eliminar un usuario por id
DELETE http://localhost:3000/api/usuarios/