### obtener todas las indumentarias
GET http://localhost:3000/api/indumentarias

### obtener una indumentaria por id
GET http://localhost:3000/api/indumentarias/

### guardar una nueva indumentaria
POST http://localhost:3000/api/indumentarias
Content-Type: application/json

{
    "marca": "68dc29f3855611417f9620d6",
    "categoria": "68f9a73df9043afdb5058ba8",
    "nombre": "Remera Deportiva Adidas",
    "stock": 50,
    "precio": 35000,
    "talle":"M",
    "color": "Negro",
    "imagen": "https://idnnutrition.com/wp-content/uploads/2024/04/13.jpg"
}

### actualizar una indumentaria por id
PUT http://localhost:3000/api/indumentarias/68e59eb3bfef201807731875
Content-Type: application/json

{
    "imagen": "https://idnnutrition.com/wp-content/uploads/2024/04/13.jpg"
}

### eliminar una indumentaria por id
DELETE http://localhost:3000/api/indumentarias/6905261f2ca1817ae2d75190
