### obtener todas las direcciones
GET http://localhost:3000/api/direcciones

### obtener una direccion por id
GET http://localhost:3000/api/direcciones/

### guardar una nueva direccion
POST http://localhost:3000/api/direcciones
Content-Type: application/json

{
    "calle": "Entre Rios",
    "nro": 1515,
    "piso": "3",
    "depto": "A",
    "codPostal": "2000",
    "ciudad": "Rosario"
}

### actualizar una direccion por id
PUT http://localhost:3000/api/direcciones/68a684c5faba127393e3fa93
Content-Type: application/json

{
    "calle": "Corrientes",
    "nro": 1212,
    "codPostal": "2000",
    "ciudad": "Rosario"
}

### eliminar una direccion por id
DELETE http://localhost:3000/api/direcciones/