### obtener todas las indumentarias
GET http://localhost:3000/api/indumentarias

### obtener una indumentaria por id
GET http://localhost:3000/api/indumentarias/

### guardar una nueva indumentaria
POST http://localhost:3000/api/indumentarias
Content-Type: application/json

{
    "marca": "68f1681b3f0a1b7e177dfc4a",
    "categoria": "68f1688e3f0a1b7e177dfc4e",
    "nombre": "Deportivo",
    "stock": 50,
    "precio": 1499.99,
    "talle": "XL",
    "color": "Gris",
    "imagen": "ruta/a/la/imagen.jpg"
}

### actualizar una indumentaria por id
PUT http://localhost:3000/api/indumentarias/
Content-Type: application/json

{
    "marca": "68dc29f3855611417f9620d6",
    "categoria": "68dc28c0a6255ac03ce0115e",
    "nombre": "Diseño espectacular",
    "stock": 20,
    "precio": 249.99,
    "talle": "L",
    "color": "Azul",
    "imagen": "ruta/a/la/nueva_imagen.jpg"
}

### eliminar una indumentaria por id
DELETE http://localhost:3000/api/indumentarias/68e59f35bfef201807731888
