### obtener todas las categorias
GET http://localhost:3000/api/categorias

### obtener una categoria por id
GET http://localhost:3000/api/categorias/68dc19de42b28580ae432e25

### guardar una nueva categoria
POST http://localhost:3000/api/categorias
Content-Type: application/json

{
    "nombre": "Pantalon",
    "descripcion": "Prenda de vestir que cubre desde la cintura hasta los pies"
}

### actualizar una categoria por id
PUT http://localhost:3000/api/categorias/68dc28c0a6255ac03ce0115e
Content-Type: application/json

{
    "nombre": "Remera",
    "descripcion": "Prenda de vestir que cubre el torso"
}

### eliminar una categoria por id
DELETE http://localhost:3000/api/categorias/68dc9097cb00e605513992ba
