### Obtener todos los pedidos
GET http://localhost:3000/api/pedidos

### Obtener un pedido por ID
GET http://localhost:3000/api/pedidos/

### Crear un nuevo pedido
POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "usuario": "68dc9ba34ccd3a30797faea4",
    "fecha": "2025-02-01",
    "estado": "pendiente",
    "pago": null,
    "envio": null
}

### Actualizar un pedido por ID
PUT http://localhost:3000/api/pedidos/69010e0ce9a75fc27f09883c
Content-Type: application/json

{
    "usuario": "68f5642c0610a3dcf6823eae",
    "fecha": "2023-10-02",
    "estado": "completado",
    "pago": null,
    "envio": null
}

### Eliminar un pedido por ID
DELETE http://localhost:3000/api/pedidos/